### ISSUE TITLE
pwncat :PORT and ssh not work[BUG]

### ISSUE THREAD

**Issue by cyal1** [calebstewart/pwncat#107]
![image](https://user-images.githubusercontent.com/33282478/120985685-6f459480-c7ae-11eb-93b5-71f99890d2e3.png)
![image](https://user-images.githubusercontent.com/33282478/120986115-d5321c00-c7ae-11eb-91bf-0cae331b2715.png)

**Comment by calebstewart** [comment]
This was indeed a problem, and I'm not sure why I hadn't experienced it before. I've pushed a fix and created a pull request. I've tested it myself, but I'll hold off to see if you want to test that branch before I merge. Thanks for reporting!

**Comment by sordidlist** [comment]
I'm not 100% certain but I think I'm running into the same issue. I tried pulling the branch with the fix (#107) but I'm still running into the bug.

In my circumstance, I'm using plain old netcat to listen on a port, and then using pwncat to connect to myself on that port. I'm able to do it with a netcat-netcat loop, but if I use pwncat, I get:

The listener:
```
$ nc -nvl 8080
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Listening on :::8080
Ncat: Listening on 0.0.0.0:8080
Ncat: Connection from 192.168.252.135.
Ncat: Connection from 192.168.252.135:43320.
 stty -echo nl lnext ^V ; export PS1=
 export PS1=;echo; echo buujA7BNqB; unset HISTFILE; export HISTCONTROL=ignorespace; unset PROMPT_COMMAND 0</dev/null; R=$?; echo HtbWSkbJ9E; echo $R; echo tNTtP7DiFA
```

This hangs here for a minute and then drops.

Pwncat:
```
$ pwncat 192.168.252.135 8080
[01:01:49] Welcome to pwncat 🐈!                                                                                                                                                                   __main__.py:127
           connection to 192.168.252.135:8080 established                                                                                                                                                 connect.py:46
[01:02:19] connection failed: channel recieve timed out: b'' 
```

I'm on Ubuntu 21.04 with nc 7.80

**Comment by calebstewart** [comment]
That's because your netcat listener is not running anything. To quote from the netcat man page:

> In the simplest usage, "nc host port" creates a TCP connection to the given port on the given target host. Your standard input is then sent to the host, and anything that comes back across the connection is sent to your standard output. This continues indefinitely, until the network side of the connection shuts down. Note that this behavior is different from most other applications which shut everything down and exit after an end-of-file on the standard input.

Read more at: https://www.commandlinux.com/man-page/man1/netcat.1.html 

The most common way to use netcat for a reverse or bind shell is the `-e` option, which executes another program and connects its stdio to the new socket. This option isn't available on all versions of netcat. You can find this syntax and many other reverse/bind shell syntax variants [here](https://www.revshells.com/) if you're shopping around

**Comment by sordidlist** [comment]
Aha. Thanks for the reference.

**Comment by cyal1** [comment]
It works with the fix (issue-107-port-ssh-not-working)
![image](https://user-images.githubusercontent.com/33282478/121112700-5804b680-c843-11eb-8637-074837314403.png)

I find another bug, sync not works
![image](https://user-images.githubusercontent.com/33282478/121112444-fd6b5a80-c842-11eb-8ee2-e1d10f89102a.png)

**Comment by calebstewart** [comment]
Whoops, I missed your other comment here. The `sync` command is no longer needed. I didn't realize it stuck around through the merge last week. I'll remove it now. Everything that happened in sync before now happens automatically.
