### ISSUE TITLE
ValueError when connecting via loopback

### ISSUE THREAD

**Issue by calebstewart** [calebstewart/pwncat#159]
## Bug Description
This is normally only a testing problem, as practically, you aren't often connecting to localhost. That being said, when connecting to a bind shell on the local machine, pwncat is unable to use `localhost`. Getting the peer name from the socket apparently results in a different return value for the loopback device vice a normal IP address.

![image](https://user-images.githubusercontent.com/7529189/126075561-6b47b57b-f24b-4616-96f4-07d6996d19e8.png)

You can use `127.0.0.1`, and it works just fine. This should be relatively easy to test/fix. I just need to figure out what exactly the expected return value is for a loopback device.

## pwncat version
Provide the output of `pwncat --version` or a commit hash if working from
a development branch.

```
$ pwncat --version
0.4.3
```

## Target System (aka "victim")
My local machine, which is an Arch Linux host.

## Steps to Reproduce
1. Start a listener with `ncat -e /bin/bash -klnvp 4444`
2. Attempt to connect to the listener with `pwncat localhost 4444`

## Expected Behavior
A connection is established in the same way as using `127.0.0.1` in place of `localhost`.

**Comment by Mitul16** [comment]
I have seen this before.
This happens when we create the bind shell using `IPv6` protocol or `AF_INET6` address family
And thus we do not get `(host, port)` pair tuple as the __return value__ which is what `pwncat` expects.

**Comment by Mitul16** [comment]
Using the port __1337__, you may receive something similar to `('::1', 1337, 0, 0)` instead of `('127.0.0.1', 1337)`

**Comment by calebstewart** [comment]
Per the Python `socket` [documentation](https://docs.python.org/3/library/socket.html#host-port)

![image](https://user-images.githubusercontent.com/7529189/126076331-b9711d0c-bdbd-4072-850d-944c7c3853a0.png)

This should be relatively easy to fix. The flow info and scope ID aren't important in this context so I'm pretty sure we can safely ignore them.

**Comment by Mitul16** [comment]
### Is this any helpful?
![Screenshot from 2021-07-18 22-59-55](https://user-images.githubusercontent.com/44923300/126076721-ad0e2b06-ebeb-471e-a226-cbc1aaf53d93.png)

**Comment by Mitul16** [comment]
I did thought about fixing it :grin: , but I thought who is using `IPv6` anyway.
And the current implementation for parsing the __host__ and __port__ using an `IPv6` address will throw an error as well.
