### ISSUE TITLE
Zope dependency issue

### ISSUE THREAD

**Issue by altjx** [calebstewart/pwncat#170]
According to the README.md file, I can install pwncat the following way:

```
python3 -m venv pwncat-env
source pwncat-env/bin/activate
python setup.py install
```

and that it requires python3.9+. However, after installing python3.9 and running the above commands, I am receiving the following error:

```
...
pwncat 0.4.3 is already the active version in easy-install.pth
Installing pc script to /usr/local/bin
Installing pwncat script to /usr/local/bin

Installed /usr/local/lib/python3.9/dist-packages/pwncat-0.4.3-py3.9.egg
Processing dependencies for pwncat==0.4.3
error: zope.interface 4.7.1 is installed but zope.interface>=5.0.0 is required by {'BTrees'}
```

Here's a video clip of it:

![output](https://user-images.githubusercontent.com/4023423/127056033-4b7a4b28-db03-4467-89b1-887c31a081e9.gif)

Running Ubuntu 20.04.2 LTS.

Any idea what I'm doing wrong here?

**Comment by altjx** [comment]
Weird. Rebooted and then ran the same steps again. Worked this time. Closing.

**Comment by calebstewart** [comment]
Do not use `sudo` to install. `sudo` clears your current `PATH` (and other environment variables) to avoid path hijacking users when using `sudo`. You are attempting to install pwncat globally, not within your virtual environment.

**Comment by altjx** [comment]
Gotcha. Thanks @calebstewart!
