### ISSUE TITLE
pwncat on BlackArch

### ISSUE THREAD

**Issue by noraj** [calebstewart/pwncat#178]
pwncat was added tto blackarch (https://github.com/BlackArch/blackarch/pull/3205), to cover the naming issue (https://github.com/calebstewart/pwncat/issues/18) we named the package and binary `pwncat-caleb`.

If you want to add install instruction for pwncat on BlackArch:

```
pacman -Syu pwncat-caleb
```

Badges:

[![Packaging status](https://repology.org/badge/vertical-allrepos/pwncat-caleb.svg)](https://repology.org/project/pwncat-caleb/versions)

```md
[![Packaging status](https://repology.org/badge/vertical-allrepos/pwncat-caleb.svg)](https://repology.org/project/pwncat-caleb/versions)
```

[![BlackArch package](https://repology.org/badge/version-for-repo/blackarch/pwncat-caleb.svg)](https://repology.org/project/pwncat-caleb/versions)

```md
[![BlackArch package](https://repology.org/badge/version-for-repo/blackarch/pwncat-caleb.svg)](https://repology.org/project/pwncat-caleb/versions)
```

**Comment by calebstewart** [comment]
Thank you for doing this! I appreciate the work. I've added packaging status and installation instructions to the readme and the documentation! :)
