### ISSUE TITLE
Pwncat does not run on Windows due to fcntl import

### ISSUE THREAD

**Issue by Reelix** [calebstewart/pwncat#191]
In multiple places, the `fcntl` module is imported.

Examples:

https://github.com/calebstewart/pwncat/blob/5ec4e35bb1887d367e5013d61888ca6a6bba7930/pwncat/util.py#L8
https://github.com/calebstewart/pwncat/blob/1d7d35e3cd27bb74ff9c37ce49b90ee2510bbfc9/pwncat/channel/socket.py#L19

This module is not available on the Windows version of python.

I suggest that either an alternate cross-platform-friendly module be used, or the `Install` section of the README file be updated to clarify that pwncat can not be installed on Windows hosts.

**Comment by calebstewart** [comment]
pwncat is not written to run on Windows. The Windows support mentioned in the documentation is for connecting to a Windows victim. pwncat must be run from a Linux host. I have no intention of supporting Windows in this way. Sorry for any inconvenience.
