### ISSUE TITLE
TODO: Ideas

### ISSUE THREAD

**Issue by JohnHammond** [calebstewart/pwncat#2]
# Windows Functionality

* Import PowerShell libraries in Full-Language Mode (PowerView, PowerUp, etc.)
* Load tools into memory (Mimikatz, Rubeus)
* Perform SpoolSample.exe privescs

# Privesc

* lxd containers
* chmod abuse -- make any GTFObin that gets a shell a SETUID binary owned by everyone
* Sudo -u#-1 CVE

# Persistence

* Create bind listener [can be done as any user, could choose from known_binaries]
* Add cronjab(user/root) 
* systemd service, init.d service [needs root]
* Add SSH keys [can be done as any user, needs ssh running]
* Install sneaky_pam [needs root, binary dependencies]
* Create SUID binary [needs root, binary dependencies]
* Chattr stomp files

# Watch

* use strace to monitor another /dev/pts session.

```
sudo strace -e write=0,1,2 -e trace=write -s1000 -fp 11440 2>&1 \
| grep --line-buffered -o '".\+[^"]"' \
| grep --line-buffered -o '[^"]\+[^"]' \
| while read -r line; do
  printf "%b" $line;
done
```

* Hijack an SSH session or another active shell (Caleb did this with SSH before..?)

# Aggression

* Spam /dev/urandom to other terminals?
* Drop SSH keys to users 
* IP ban (refer to Red Team Field Manual)
* Flush firewall rules

# File transfer

* FTP, TFTP, SMB
* DNS exfil
* ICMP exfil

# Stealth

* Clear log files (refer to Red Team Field Manual)

# Meme

* Terminal parrot
* ponysay
* cowsay
* wall 
* write to user terminals
* Forkbomb
* Ransomware (hash/encrypt all files)

# Custom

* Force overwrite of KoTH `king.txt` file?
* Scape inbound SSH connections

# Crazy ideas

* Generate static binaries for the specific architecture and release
* Port forward
* Pivot through host to reach Internet

**Comment by trevorbryant** [comment]
@JohnHammond, I'm going to let you manage this issue as you're contributing development and application architecture with Caleb.
