### ISSUE TITLE
pam persist

### ISSUE THREAD

**Issue by CodeXTF2** [calebstewart/pwncat#20]
I did persist -i -m pam and it seems to have been installed, but when I log in with any user with the backdoor password it doesnt let me in. Am I doing something wrong? Also, even when running as root removing the persistence with tamper gives me an insufficient permission error. Sorry if I did something wrong, but I followed the commands as in the documentation.

UPDATE: 
issue is caused by SELinux. Needs to be set to permissive to work.
Can be easily fixed by adding an os.system command in the pam.py script to set SELinux to permissive. Could trigger alerts so not an ideal solution, but it works.
pam logs:

Jun 28 18:06:18 localhost sshd[12335]: PAM adding faulty module: /usr/lib64/security/pam_succeed.so
Jun 28 18:06:20 localhost sshd[12335]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"
Jun 28 18:15:46 localhost sshd[16556]: PAM unable to dlopen(/usr/lib64/security/pam_succeed.so): /usr/lib64/security/pam_succeed.so: failed to map segment from shared object: Permission denied
Jun 28 18:15:46 localhost sshd[16556]: PAM adding faulty module: /usr/lib64/security/pam_succeed.so
Jun 28 18:15:48 localhost sshd[16556]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"

**Comment by calebstewart** [comment]
Yes, `SELinux` will cause this to fail. The install will work, but it won't actually be allowed to run. I should be able to add a check in for SELinux being set to enforce mode, and not install in the case. I don't think just automatically disabling SELinux is a good idea from this module. If the user wants to set permissive mode, they can do that separately, but the persistence shouldn't install or should print a warning in the case of SELinux enforce-mode.

**Comment by CodeXTF2** [comment]
Agreed. A warning sounds like a good idea :D
