### ISSUE TITLE
Pwncat broken on Parrot OS

### ISSUE THREAD

**Issue by mgeddert** [calebstewart/pwncat#201]
## Bug Description
On Parrot OS any attempt to create a listener fails, regardless if the python interpreter shipped
with the distribution (3.9.2) or a fresh compiled latest version (3.9.7) is used.

pwncat fails to bind to any port with:

connection failed: generic channel failure  

...then drops you into your local pwncat shell. 

## pwncat version
Provide the output of `pwncat --version` or a commit hash if working from
a development branch.

```
$ pwncat --version
0.4.3
```

# Sorry I really gotta learn Markdown !

**Comment by calebstewart** [comment]
From our E-mail conversation, you mentioned that you use the following command:

```sh
pwncat -m windows -l 4444
```

However, this is not exactly correct. The command your looking for is:

```sh
# You need to tell pwncat you are specifying a port number
pwncat -m windows -lp 4444
# The equivalent command with long-form options is this
pwncat --platform windows --listen --port 9999
```

The reason it is failing is that the first positional argument is assumed to be a connection string. The port number is intended to be an argument to the `--port` option, but in the absence of `--port`, it is treated as a positional argument instead.

**Looking back at the documentation, it appears there's a typo [here](https://pwncat.readthedocs.io/en/latest/usage.html#id1).**
![image](https://user-images.githubusercontent.com/7529189/134053855-12343b2d-6ea1-4a7f-9b38-088b14d75c38.png)

I'll write up a fix for the documentation later this evening. Also, I'll look into making that error message a little more helpful. Thanks for reporting!

> Sorry I really gotta learn Markdown !

No problem at all! Thanks for making the effort :smiley:

**Comment by mgeddert** [comment]
😲 wow I‘ll get out of bed and test !

**Comment by mgeddert** [comment]
Yes ! Yes ! Wonderful !

Good Night for Now,
Michael

**Comment by mgeddert** [comment]
Thanks a lot ! That really helped ! When I connect with a windows machine I
get a

windows.enumerate.domain:
usr/local/master/lib/python3.9/dist-packages/pwncat/data/PowerSploit/Recon/Get-ComputerDetail.ps1:
psmodule not found

I guess that is in the C2 Assembly, right ? Also "sessions" gives me a
traceback....Hmm I'll keep trying.
I'll have to play and roadtest a lot with pwncat.

Cheers,
Michael

Am Di., 21. Sept. 2021 um 07:56 Uhr schrieb Caleb Stewart <
***@***.***>:

**Comment by Mitul16** [comment]
@mgeddert 
> windows.enumerate.domain:
usr/local/master/lib/python3.9/dist-packages/pwncat/data/PowerSploit/Recon/Get-ComputerDetail.ps1:
psmodule not found

You can `Pre-download all Windows builtin plugins` using `pwncat --download-plugins`
<hr>

> I guess that is in the C2 Assembly, right ? Also "sessions" gives me a
traceback....Hmm I'll keep trying.
I'll have to play and roadtest a lot with pwncat.

Could you please elaborate on this?
What kind of **Error** did you receive?

**Comment by mgeddert** [comment]
I have downloaded the plugins several times.

I‘ll test tomorrow with a fresh box….

**Comment by mgeddert** [comment]
Right after the victim connects, when the listener screen should  change and give me a list of sessions i get a traceback. Right before that it prints the msg about the missing module. I‘ll have a traceback and maybe even a screen capture for you tomorrow. 

Transcribed from the Nether

**Comment by calebstewart** [comment]
That error isn't from the plugins. PowerSploit should be included in the installed Python module. I don't know why it wouldn't have been installed with pwncat. I can't really help diagnose without a copy of the output including the traceback, which you mentioned you'll have tomorrow.

**Comment by mgeddert** [comment]
I was rerouted to install new switches onsite, no pwncat playtime today. Tomorrow for sure.

Regards
