### ISSUE TITLE
add missing license

### ISSUE THREAD

**Issue by kingrodriguez** [calebstewart/pwncat#214]
Currently there is no license attached to the repo.

That might bring up some legal issues.

for example:
* you use software that requires leaving a note of the author
* if i wanna use your software, i actually need permission to to that via a license.

Because i had to take care of software licensing in the past i have a little bit of knowledge on the topic.

If you are interested in attaching a license, check for the possible licenses and can make a PR.

> Note: Be aware, software licensing is a mess!.

**Comment by JaeTLDR** [comment]
if possible, please license with BSD or MIT rather than the notoriously messy GPL

**Comment by kingrodriguez** [comment]
that depends a little bit on the licenses of the dependencies. if one of them has a strong copyleft (e.g. `[GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)` it will be hard to avoid that. i will start check it, if they want a license (it might be a bit work)

**Comment by calebstewart** [comment]
I just released `v0.5.0` which added the MIT license to the project. See [Release Notes](https://github.com/calebstewart/pwncat/releases/tag/v0.5.0) for more info.
