### ISSUE TITLE
consider more advanced env handling

### ISSUE THREAD

**Issue by kingrodriguez** [calebstewart/pwncat#215]
currently the project uses pip for handling dependencies. there are superior tools out there, that can help handling dependencies and venvs. also nobody needs to write a setup.py in the 21st century anymore =)

my suggestions are:

* [poetry](https://python-poetry.org/) (my recommendation)
    * dependency resolving
    * venv handling
    * building python packages
    * uploading to pypi
    * uses pyproject.toml (PEP 621)
    * scopes for dev and production env
* [pipenv](https://pypi.org/project/pipenv/)
    * dependency resolving
    * venv handling
    * easy deployment within other systems (e.g. docker)
    * scopes for dev and production env

if you are interested in changing the env handling, chose one and i can open a PR.

**Comment by calebstewart** [comment]
I've just released `v0.5.0` which moved to Poetry and now pushes the project to PyPI under the name `pwncat-cs`. The entrypoint was also changed to `pwncat-cs` to deconflict with Cytopia's pwncat. More details can be found in the [Release Notes](https://github.com/calebstewart/pwncat/releases/tag/v0.5.0).
