### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pwncat-cs

### ISSUE THREAD

**Issue by nsmagic** [calebstewart/pwncat#223]
Hello. 

When I want to install Pwncat it gives me this error message.
I tried on ubuntu 18.04, debian 9, 10, 11

# pip install pwncat-cs
ERROR: Could not find a version that satisfies the requirement pwncat-cs (from versions: none)
ERROR: No matching distribution found for pwncat-cs

## pwncat version
Lasted

**Comment by Mitul16** [comment]
Hey @nsmagic, what is the `python` version you are using?
[Here](https://pypi.org/project/pwncat-cs/) you can see, `pwncat-cs` *Requires: Python >=3.9, <4.0*

![Screenshot from 2021-12-07 17-34-08](https://user-images.githubusercontent.com/44923300/145026261-439a0c4f-ba5b-4263-a032-28ccf4da5798.png)

## Using Python 3.8.0 and 3.9.2
![Screenshot from 2021-12-07 17-29-39](https://user-images.githubusercontent.com/44923300/145026268-b393f07b-bfa8-44fb-a532-f96478e061ff.png)

![Screenshot from 2021-12-07 17-31-07](https://user-images.githubusercontent.com/44923300/145026265-e2597ace-bfe7-4319-9568-9fce9e813edf.png)

**Comment by nsmagic** [comment]
Ok. 
The command is pip3.9 install pwncat-cs 

Thanks

**Comment by calebstewart** [comment]
This is simply a case of incorrect Python version. Sadly, `pip` provides a completely unhelpful error on output, but I can't fix that. As mentioned above and in the readme, **pwncat requires python 3.9 or above**.

**Comment by calebstewart** [comment]
Just a fun fact for anyone sliding through this issue, there as a PR earlier this year to improve the error messages from pip [here](https://github.com/pypa/pip/pull/9708), but it seems it is stalled. :frowning_face: If we're lucky, [this](https://github.com/pypa/pip/issues/10421) newer all-around output/error/diagnostic issue may provide some much needed pip output improvements, though.
