### ISSUE TITLE
pwncat-cs installation problem

### ISSUE THREAD

**Issue by Aziz1337** [calebstewart/pwncat#286]
Hi guys whenver i try to launch pwncat-cs  I get this error. Can someone help me please
┌──(kali㉿kali)-[~]
└─$ pwncat-cs                      
Traceback (most recent call last):
  File "/usr/local/bin/pwncat-cs", line 5, in <module>
    from pwncat.__main__ import main
ModuleNotFoundError: No module named 'pwncat'

![pwncatcs](https://github.com/calebstewart/pwncat/assets/92120389/b7722c5b-cd31-4138-a669-d50856c92827)

**Comment by shadowe1ite** [comment]
> Hi guys whenver i try to launch pwncat-cs I get this error. Can someone help me please ┌──(kali㉿kali)-[~] └─$ pwncat-cs Traceback (most recent call last): File "/usr/local/bin/pwncat-cs", line 5, in from pwncat.**main** import main ModuleNotFoundError: No module named 'pwncat'
> 
> ![pwncatcs](https://private-user-images.githubusercontent.com/92120389/342123084-b7722c5b-cd31-4138-a669-d50856c92827.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODQxMTAsIm5iZiI6MTczMDM4MzgxMCwicGF0aCI6Ii85MjEyMDM4OS8zNDIxMjMwODQtYjc3MjJjNWItY2QzMS00MTM4LWE2NjktZDUwODU2YzkyODI3LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE0MTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODE2NjZkODY2ZWZiZWRmNzI3Yzg2NzA1YTlmMmViZjZlZmM5YTRlYmNmMGNkODQ0ODY2MWI5YjlkODg4ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jnEXnuKXYac0IcaWMcHFQ3TpT1AcSn-XEI1501BMq7w)

how did you fixed it ?
