### ISSUE TITLE
Unhandled decoding error in password enumeration

### ISSUE THREAD

**Issue by Pheelbert** [calebstewart/pwncat#32]
https://github.com/calebstewart/pwncat/blob/95877fa160bcc3822ac040143dace505d7b5b37f/pwncat/enumerate/passwords.py#L66

I've crossed this issue, I believe simply adding a try catch would fix it.

**Comment by calebstewart** [comment]
I added a try-catch around that decode in c81d5fd. This should prevent the issue from returning. Thanks for bringing it up, and please re-open if you somehow still see this popping up!
