### ISSUE TITLE
error while trying to enum or privesc 

### ISSUE THREAD

**Issue by BlackSnufkin** [calebstewart/pwncat#38]
Traceback (most recent call last):

 File "/root/Snufkin/tools/pwncat/pwncat-env/lib/python3.8/site-packages/pwncat-0.3.1-py3.8.egg/pwncat/commands/__init__.py", line 215, in run                                            
    212                 if line == "":                                                                                                                                                    
    213                     continue                                                                                                                                                      
    214                                                                                                                                                                                   
  ❱ 215                 self.dispatch_line(line)                                                                                                                                          
    216             # We used to catch only KeyboardException, but this prevents a                                                                                                        
    217             # badly written command from completely killing our remote                                                                                                            
    218             # connection.                                                                                                                                                         
 File "/root/Snufkin/tools/pwncat/pwncat-env/lib/python3.8/site-packages/pwncat-0.3.1-py3.8.egg/pwncat/commands/__init__.py", line 290, in dispatch_line                                  
    287                 args = line                                                                                                                                                       
    288                                                                                                                                                                                   
    289             # Run the command                                                                                                                                                     
  ❱ 290             command.run(args)                                                                                                                                                     
    291                                                                                                                                                                                   
    292             if prog_name:                                                                                                                                                         
    293                 command.parser.prog = prog_name                                                                                                                                   
 File "/root/Snufkin/tools/pwncat/pwncat-env/lib/python3.8/site-packages/pwncat-0.3.1-py3.8.egg/pwncat/commands/enumerate.py", line 187, in run                                           
    184             return                                                                                                                                                                
    185                                                                                                                                                                                   
    186         if args.action == "show":                                                                                                                                                 
  ❱ 187             self.show_facts(args.type, args.provider, args.long)                                                                                                                  
    188         elif args.action == "flush":                                                                                                                                              
    189             self.flush_facts(args.type, args.provider)                                                                                                                            
    190         elif args.action == "report":                                                                                                                                             
 File "/root/Snufkin/tools/pwncat/pwncat-env/lib/python3.8/site-packages/pwncat-0.3.1-py3.8.egg/pwncat/commands/enumerate.py", line 423, in show_facts                                    
    420         ) as progress:                                                                                                                                                            
    421             task = progress.add_task("", status="initializing")                                                                                                                   
    422             for typ in types:                                                                                                                                                     
  ❱ 423                 for fact in pwncat.victim.enumerate.iter(                                                                                                                         
    424                     typ, filter=lambda f: provider is None or f.source == provider                                                                                                
    425                 ):                                                                                                                                                                
    426                     progress.update(task, status=str(fact.data))                                                                                                                  
 File "/root/Snufkin/tools/pwncat/pwncat-env/lib/python3.8/site-packages/pwncat-0.3.1-py3.8.egg/pwncat/enumerate/__init__.py", line 118, in iter                                          
    115                     if self.exist(enumerator.provides, dummy_name):                                                                                                               
    116                         continue                                                                                                                                                  
    117                                                                                                                                                                                   
  ❱ 118                 for data in enumerator.enumerate():                                                                                                                               
    119                     try:                                                                                                                                                          
    120                         fact = self.add_fact(                                                                                                                                     
    121                             name, data, enumerator.name, exist_ok=False                                                                                                           
 File "/root/Snufkin/tools/pwncat/pwncat-env/lib/python3.8/site-packages/pwncat-0.3.1-py3.8.egg/pwncat/enumerate/passwords.py", line 73, in enumerate                                     
     70             if len(line) < 3:                                                                                                                                                     
     71                 continue                                                                                                                                                          
     72             path = line[0]                                                                                                                                                        
  ❱  73             lineno = int(line[1])                                                                                                                                                 
     74             content = ":".join(line[2:])                                                                                                                                          
     75                                                                                                                                                                                   
     76             password = None                                                                                                                                                       

ValueError: invalid literal for int() with base 10: ''

**Comment by calebstewart** [comment]
Can you tell me about the system you are using this on? I can add a try-except around that, but it's indicative of a possible underlying issue, since `grep` should have a standard output format.

Also, if you are posting any output or code snippets, please wrap them in three backticks, so it formats properly. It's very hard to read otherwise. Thanks.

**Comment by BlackSnufkin** [comment]
sorry for this out put my bad 
and i am using Kali Linux 2019.4 with the latest update 
and i installed pwncat with python venv

**Comment by calebstewart** [comment]
Sorry, I mispoke there. Can you tell me what system you are _targeting_? Or at the least, what type of system (e.g. distribution).

**Comment by BlackSnufkin** [comment]
the targeted syatem was ubuntu 20.04 with the latest update

בתאריך יום ב׳, 20 ביול' 2020, 23:55, מאת Caleb Stewart ‏<
notifications@github.com>:

**Comment by BlackSnufkin** [comment]
the targeted system was ubuntu 20.04 with the latest update

**Comment by calebstewart** [comment]
I do apologize for the long delay on this. In any case, I still can't reproduce the error. It looks like the output of grep is either non-standard or there was some kind of corruption in the response.

That being said, I added an exception handler to handle this fluke gracefully, so it shouldn't cause complete failures anymore if it happens again (commit: 57809be)

**Comment by RichCompton** [comment]
Getting command not found while using pwncat. Installed using pipx. Seemed like an elegant solution to manage venvs and launch pwncat from command line. Could this be pipx messing up or what?

**Comment by trevorbryant** [comment]
If you're using the latest version of pwncat then those former commands have been replaced. See [Automated Privilege Escalation](https://pwncat.readthedocs.io/en/latest/privesc.html) section of the documents for the latest and greatest commands. 

Here's an example of an automated privesc.
```bash
(local) pwncat$ run escalate.auto exec
```

Let me know if this works!
