### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aram535** [calebstewart/pwncat#39]
**Describe the bug**
Error while running app

**Describe the target system**
CentOS 8, 64-bit x86
Python 3.6.8

**To Reproduce**

1. clone (I added --depth=1 but I doubt that would cause this)
2. cd pwncat 
3. python -m venv env
4. source env/bin/activate 
5. python setup.py install  (no errors or warnings produced)
6. ./pwncat --help

**Expected behavior**
It should produce the help output

** Output of error ** 
```
Traceback (most recent call last):
  File "/opt/red/pwncat/env/bin/pwncat", line 11, in <module>
    load_entry_point('pwncat==0.3.1', 'console_scripts', 'pwncat')()
  File "/opt/red/pwncat/env/lib64/python3.6/site-packages/pwncat-0.3.1-py3.6.egg/pwncat/__main__.py", line 29, in main
    shlex.join(["connect"] + sys.argv[1:]), prog_name="pwncat"
AttributeError: module 'shlex' has no attribute 'join
```

**Comment by JohnHammond** [comment]
It looks like you are using Python 3.6.  The "shlex" module did not have support for the "join" method until a later version. If you update to Python 3.8, this problem should be resolved.

**Comment by aram535** [comment]
Thank you.   I don't see a CONTRIBUTING file in the repo.  Do you want a PR for an update on install script to warn people about the minimum required version of python?
