### ISSUE TITLE
zsh support

### ISSUE THREAD

**Issue by pitust** [calebstewart/pwncat#54]
**Is your feature request related to a problem? Please describe.**
The prompt is broken in zsh

**Describe the solution you'd like**
Make the prompt look similar to what `bash` does.

**Describe alternatives you've considered**
Manually setting the prompt and just using bash.

**Additional context**
this seems to do it in both bash and zsh:
```
export PS1='$(echo -n '"'"' \033[01;31m(remote)\033[00m \033[01;33m'"$(whoami)@$(hostname)"'\033[00m:\033[01;36m'"${PWD/$HOME/~}"'\033[00m$ '"'"')'
```
Still doesn't work in dash though.

**Comment by pitust** [comment]
in dash, this is 99.9% acceptable:
```
export PS1='$(command printf "\033[01;31m(remote)\033[0m \033[01;33m$(whoami)@$(hostname)\033[0m:\033[1;36m$PWD\033[0m$ ")'
```

**Comment by pitust** [comment]
The prompt I made new prompt is additionally 100% posix-compliant and should work in ALL minimalist shells. The only difference is that the home directory is not replaced with `~`. It is pretty hard to do while:
 a) staying dependency-free
 b) not using bash
That is the only difference i could find.

**Comment by calebstewart** [comment]
I just reviewed your PR. One small question over there before I'm comfortable merging. As I said on the PR, I appreciate the hand! :)
