### ISSUE TITLE
[BUG] Unable to ssh into a box

### ISSUE THREAD

**Issue by jfunction** [calebstewart/pwncat#58]
Trying to connect over ssh to a system gives an error:
```
pwncat --ssh --user {SomeUser} --password {SomePass} -H {SomeIP}
Traceback (most recent call last):
  File "/home/me/.local/share/virtualenvs/proj-2l1lFwst/bin/pwncat", line 33, in <module>
    sys.exit(load_entry_point('pwncat', 'console_scripts', 'pwncat')())
  File "/home/me/.local/share/virtualenvs/proj-2l1lFwst/src/pwncat/pwncat/__main__.py", line 28, in main
    pwncat.victim.command_parser.dispatch_line(
  File "/home/me/.local/share/virtualenvs/proj-2l1lFwst/src/pwncat/pwncat/commands/__init__.py", line 290, in dispatch_line
    command.run(args)
  File "/home/me/.local/share/virtualenvs/proj-2l1lFwst/src/pwncat/pwncat/commands/connect.py", line 229, in run
    pwncat.victim.connect(chan)
  File "/home/me/.local/share/virtualenvs/proj-2l1lFwst/src/pwncat/pwncat/remote/victim.py", line 275, in connect
    hostname_path = self.run("which hostname").strip().decode("utf-8")
  File "/home/me/.local/share/virtualenvs/proj-2l1lFwst/src/pwncat/pwncat/remote/victim.py", line 1041, in run
    sdelim, edelim = self.process(cmd, delim=wait, timeout=timeout)
  File "/home/me/.local/share/virtualenvs/proj-2l1lFwst/src/pwncat/pwncat/remote/victim.py", line 1095, in process
    data = self.client.recv(len(command), socket.MSG_PEEK)
TypeError: recv() takes 2 positional arguments but 3 were given
```

Strange because I counted 2 arguments there, but usually this error indicates something with `self` 🤷

Feeling lazy, I thought the least I could do was stick a `print(self.client)` at line 1094 to help debug (if needed):
```
<paramiko.Channel 0 (open) window=2097096 -> <paramiko.Transport at 0x9c105c70 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>
```
And indeed Channel.recv takes 1 argument fewer than what is being passed in here.
http://docs.paramiko.org/en/stable/api/channel.html#paramiko.channel.Channel.recv

Not immediately sure how to proceed since I'm unfamiliar with the code, but I'm sure this is sufficient info for a fix? 

My setup:
```
pyenv install 3.8.2
pipenv install -e git+https://github.com/calebstewart/pwncat.git#egg=pwncat
pipenv graph | grep paramiko
  - paramiko [required: ==2.7.1, installed: 2.7.1]
```

**Comment by calebstewart** [comment]
Sorry for the confusion, and I appreciate the digging you did. Paramiko's Channel interface was *almost* identical to a standard socket, but missing this optional parameter to recv. As a result, I added the parameter to Paramiko and submitted a pull request... alas, they accepted the PR but still haven't merged the request...

As a result, pwncat depends on this forked version of paramiko in the meantime (FYI this will hopefully change with some modifications I'm making soon). I'm reworking the documentation right now for the new module interface anyway, so I'll make sure to add a more prominent warning about this.

The forked version of paramiko is required in the `setup.py` script, however if you already had paramiko installed prior to install pwncat, `pip` would have thought that the requirement was already met :disappointed: You can fix it by uninstalling paramiko and installing the forked copy (https://github.com/calebstewart/paramiko).

**Comment by jfunction** [comment]
Interesting - I used `pipenv` on a fresh python install so after reading your comment looked into how things still managed to get borked. After digging I learned that in order for `pipenv` to properly resolve `dependency_links`, it requires an environment variable: 
`PIP_PROCESS_DEPENDENCY_LINKS=1` 

derp. 

Thanks for explaining the issue.

**Comment by calebstewart** [comment]
Actually, that might help. That might be what's causing the issue for others. This caused me to do some more digging, and it looks like there's a separate option for processing dependency links in `pip` as well. I don't know why I haven't encountered this. I also found [this](https://stackoverflow.com/questions/12518499/pip-ignores-dependency-links-in-setup-py). One of the comments on an answer mentions using `install_requires = [ "package @ https://github.com/user/project/tarball/master.tar.gz" ]` instead of `dependency_links`. I'll do some testing. This may fix the issue for others as well.

**Comment by jfunction** [comment]
Yeh so after all that I ended up manually installing each dependency link before installing `pwncat` to get it to work. Somehow setting the environment variable wasn't enough. I recall the `pipenv` developer saying that `pipenv` is just a wrapper around `pip` which supports `Pipfile.lock`. Given that information, coupled with the comment from `turtlemonvh` on that link, it seems that "If same version was on pypi and declared in the egg name in dependency_links, pip would ignore the dependency_links version and just fetch from pypi."

I think you're onto something with `install_requires` but I'm a little under time pressure from work at the moment to test myself. Good luck.

**Comment by calebstewart** [comment]
I've added a runtime check to print a helpful message when this problem appears until I can find a permanent solution, and made a separate issue to hopefully prevent future issues like this from cropping up (#60)
