### ISSUE TITLE
[BUG] SSH Both using Password and Identity file error about positional arguments

### ISSUE THREAD

**Issue by Arekku5u** [calebstewart/pwncat#59]
_If you are pasting terminal output or code snippets, place them in a code block (three backticks) in accordance with Markdown formatting for easier reading_

**Describe the bug**
Trying to use the programs ssh capabilities following prompts for giving it a username and password and then when the host option is added it results in an error as seem below

```python
TypeError: recv() takes 2 positional arguments but 3 were given
````
It might be a really simple fix that I'm missing, but I can't seem to find a fix for it anywhere.

**Describe the target system**
The machine is Vulnix from vulnhub 
Linux vulnix 3.2.0-29-generic-pae #46-Ubuntu SMP Fri Jul 27 17:25:43 UTC 2012 i686 i686 i386 GNU/Linux

**To Reproduce**
I had already uploaded ssh keys and tested that they work with normal ssh 
using pwncat in the following syntax ```pwncat --ssh -H vulnix -u vulnix -i id_rsa``` and also there is a user who's password is easy to bruteforce using the following syntax ```pwncat --ssh -H vulnix -u user -P letmein``` results in the same error 

**Expected behavior**
Was expecting both commands to result in a shell of some sort. 

**Screenshots**

The first two screenshots are just to confirm that the methods work normally 

![working_p](https://user-images.githubusercontent.com/41472019/93293179-b3f95c00-f82a-11ea-848d-7890539da9d9.png)

![working_s](https://user-images.githubusercontent.com/41472019/93293221-d1c6c100-f82a-11ea-8120-279077cc8606.png)

The pwncat results - 

![password](https://user-images.githubusercontent.com/41472019/93293238-df7c4680-f82a-11ea-815d-c3ab2649609d.png)

![ssh](https://user-images.githubusercontent.com/41472019/93293232-dab79280-f82a-11ea-8984-1ca777a63d38.png)

**Comment by calebstewart** [comment]
This happens because python is not installing the requested version of paramiko from the `setup.py` script. I'm working on a fix for this, but in the meantime I've added a runtime check to ensure you get a normal error message which instructions on how to fix it. I've also opened #60 to help future users. 

For the sake of documentation, you can fix this problem with `pip install -U git+https://github.com/calebstewart/paramiko`.

**Comment by calebstewart** [comment]
I'm closing this issue in an effort to consolidate reporting into the the other issue. Please comment there if the recommended fix doesn't work for you. Thanks for the report!
