### ISSUE TITLE
[BUG] Incorrect processing of sudo entries with multiple commands

### ISSUE THREAD

**Issue by calebstewart** [calebstewart/pwncat#71]
**Describe the bug**
It appears pwncat is failing to process sudo entries with multiple command entries again. I thought this was fixed.

![image](https://user-images.githubusercontent.com/7529189/97651388-413aed80-1a32-11eb-9924-4200c7322df4.png)

**Describe the target system**
Private CTF game. Above screenshot documents the sudo privileges that were observed. pwncat did not identify them in enumeration or escalation.

**Comment by trevorbryant** [comment]
@calebstewart pretty sure you fixed this, right?

**Comment by calebstewart** [comment]
I'm 2 months late, and also pretty sure this was fixed... If anyone stumbles on this and is having problems, please let me know, but I distinctly remember working on this problem.
