### ISSUE TITLE
[BUG] Missing dependency: base64io

### ISSUE THREAD

**Issue by Marnick39** [calebstewart/pwncat#72]
**Describe the bug**
When installing on Kali Linux (Debian 5.7.6-1kali2) using:
`pip3 install git+https://github.com/calebstewart/pwncat.git`

I get the following error:
`  File "/home/<user>/.local/lib/python3.8/site-packages/pwncat/gtfobins.py", line 4, in <module>
    from base64io import Base64IO
ModuleNotFoundError: No module named 'base64io'`

**To Reproduce**
1. Install on Debian 5.7.6 using `pip3 install git+https://github.com/calebstewart/pwncat.git`
2. sudo ln -s /home/<user>/.local/bin/pwncat /usr/bin/
3. run `pwncat`

**Expected behavior**
I expected not to need to install base64io manually, using `pip install base64io`. This does fix the error.

**Comment by Marnick39** [comment]
Full installation output [here](https://pastebin.com/gi3f84RY), pass:`7PNCjJbuDC`

**Comment by Marnick39** [comment]
I suspect this is happening for the same reason paramiko isn't (always) installing automatically, both depend on your fork:
git+https://github.com/JohnHammond/base64io-python
git+https://github.com/calebstewart/paramiko
(source: requirements.txt)

Paramiko was also not installed automatically, but that is a known issue and was handled 'correctly' by printing the related error: 
```
error: pwncat requires a custom fork of paramiko. This can be installed with `pip install __main__.py:26
           -U git+https://github.com/calebstewart/paramiko` 
```

How would you like to approach this? Add a similar error for base64io, or is the dependency on your own fork being removed in the near future?

**Comment by calebstewart** [comment]
I haven't seen this happen yet, but I believe it's basically the same issue as `paramiko`. The same solution should work here. I'm fairly certain I will be able to fully remove this dependency with the updates I'm working on now. I'll add a reference to the README in the meantime, though. Thanks for the report!

**Comment by calebstewart** [comment]
I realize in hindsight that you didn't mention actually getting around the problem yourself. As mentioned in the README update, you can manually install the fork with:

```sh
pip install git+https://github.com/JohnHammond/base64io-python
```

And that should allow you to run `pwncat` as normal.
