### ISSUE TITLE
TODO: DNS exfil

### ISSUE THREAD

**Issue by Marnick39** [calebstewart/pwncat#73]
How do you guys envision the DNS exfil happening? 

Would you like to create an option to make everything happen over DNS (tcp-over-dns style), allow only for file/data exfil via DNS, ..?

**Comment by calebstewart** [comment]
I think it would be cool to implement everything over DNS. The idea for the Channel interface was to allow this. Basically, implementing a new `Channel` class which implements DNS based communication would be ideal, but I'm not sure how to do it, and haven't spent any time trying to develop it. 

This interface is currently functioning in the `platforms` branch, and an initial attempt of it can be seen in the `master` branch at `pwncat/channel/`. Currently, I'm using the `selectors` module in python to perform async file I/O for the raw mode prompt, so the channels themselves must implement the `fileno` method (e.g. have an underlying file descriptor to reference for epoll/select). I'm not sure how that fits in with C2 over DNS (I'm admittedly not familiar with actually implementing that). If this causes problems, I expected to have to move to a different model for performing the asynchronous I/O for raw mode (possibly having to implement part of that IO loop in async).

**Comment by calebstewart** [comment]
This isn't on the roadmap currently. We may revisit this at a later time. For now, we want to focus on solidifying the framework and fleshing out the multiplatform support.
