### ISSUE TITLE
Docker Image in DockerHub 

### ISSUE THREAD

**Issue by mayankkholia** [calebstewart/pwncat#80]
Anyone please add a public docker image to dockerhub, it would help people like me who have issues while installing locally or building the image by Dockerfile.

**Comment by trevorbryant** [comment]
@mayankkholia, thanks for being patient with us.

There is currently a [Dockerfile](https://github.com/calebstewart/pwncat/blob/master/Dockerfile) in the repository to build from. Unless @calebstewart sets up an image on the hub, this should work in the meantime.

**Comment by calebstewart** [comment]
I'm sorry this took so long. I put this together today. @mayankkholia, please let me know if it works for you!

[DockerHub - pwncat](https://hub.docker.com/r/calebjstewart/pwncat)

**Comment by trevorbryant** [comment]
@mayankkholia, were you satisfied with the docker image?

**Comment by trevorbryant** [comment]
@mayankkholia I'm closing this issue as it has gone stale. So far, the image works for me but that doesn't mean that is the same case for you.

Feel free to re-open the issue if needed in the future.
