### ISSUE TITLE
Shlex has not attribute join

### ISSUE THREAD

**Issue by jimmyfish** [calebstewart/pwncat#81]
```
(venv) root@ip-10-10-231-252:/opt/pwncat# pwncat 
Traceback (most recent call last):
  File "/opt/pwncat/venv/bin/pwncat", line 33, in <module>
    sys.exit(load_entry_point('pwncat==0.3.1', 'console_scripts', 'pwncat')())
  File "/opt/pwncat/venv/lib/python3.6/site-packages/pwncat-0.3.1-py3.6.egg/pwncat/__main__.py", line 65, in main
    shlex.join(["connect"] + sys.argv[1:]), prog_name="pwncat"
AttributeError: module 'shlex' has no attribute 'join'
```

I am getting this error when try to run `pwncat` and `pwncat "ssh://user@$IP"`

Am I get this correctly installed ? because I did the same thing on my PC and it's seems work flawlessly, but for newly pulled script and (perhaps) new installed version python, it didn't.

**Comment by Eergn** [comment]
i have the same problem man hmm?

**Comment by calebstewart** [comment]
That is a `python3.8` feature. You are likely running `python3.6` or
`python3.7`.

**Comment by jimmyfish** [comment]
Is it possible that you update readme file that mention it required specific python version ? 

It's indeed I can figured it out, but needs consideration for newly person too, please.

Thanks.

**Comment by calebstewart** [comment]
Definitely. I will make that change and close this issue once it's done!

**Comment by jimmyfish** [comment]
Yes please, caleb

**Comment by jimmyfish** [comment]
Thank you Caleb, it really helps the beginner one, we really love your works !
