### ISSUE TITLE
[BUG] CFFI error @ the installation

### ISSUE THREAD

**Issue by traumatism** [calebstewart/pwncat#84]
**Describe the bug**
i just can't install pwncat, very sad.

**Describe the target system**
That a kali linux running on wsl

**To Reproduce**
https://asciinema.org/a/EB752Zc77W1JTPCdpDbUb0GyC

**Comment by trevorbryant** [comment]
@traumatism very cool to see the use of asciinema, and WSL in your issue!

Let's rule out of this is an environmental issue as it seems the `ffi.h` error is thrown. the pwncat dependencies in [requirements](https://github.com/calebstewart/pwncat/blob/master/requirements.txt) and [setup.py](https://github.com/calebstewart/pwncat/blob/master/setup.py) does not have the package `libffi-dev` included as a dependency. Can you install that and see if reinstalling pwncat succeeds? You should be able to install the package through `apt install libffi-dev`.

Let us know how that works out.

**Comment by traumatism** [comment]
hey trevor, thanks for your fast answer !!

cffi problem is fixed (tyy)
now its base64io john's library (https://asciinema.org/a/rvC7V7iKsotpdX4MXTGtFyDX3)

**Comment by trevorbryant** [comment]
@traumatism This one is mentioned in the [README](https://github.com/calebstewart/pwncat#base64io) with the workaround.

Try this and let me know.

**Comment by traumatism** [comment]
it works now! big big thanks ! (have a nice day)
