### ISSUE TITLE
[BUG] no newline - THM Linux PrivEsc

### ISSUE THREAD

**Issue by CheeseC4k3** [calebstewart/pwncat#85]
**Describe the bug**
after a shell has spawned, I can type a command but not see it. When I hit enter it executes the command, but there are no newlines.
**Describe the target system**
I encountered this issue on THM box Linux PrivEsc, in the crontab section, when I set up a listener for the tar * privesc.

**To Reproduce**
1. Go to THM Linux PrivEsc Task 10  Cron Jobs - Wildcards
2. follow all the steps
3.  set up a pwncat listener instead of nc

**Expected behavior**
a normal behaving shell
**Screenshots**
![image](https://user-images.githubusercontent.com/52067790/107524116-bc757900-6bb5-11eb-832c-cbf43ef4870f.png)

**Comment by calebstewart** [comment]
We might need to get more explicit with the `stty` settings apply (right now we just change the things we need, and assume the rest is the "default" setup). Explicitly applying a set of `stty` settings would probably fix this. I'll look into it when I get home from work today.

**Comment by calebstewart** [comment]
In the meantime, if you still have the machine open, can you run `stty sane` or `reset` from the remote prompt and tell me if either of those fixe it? If not, I totally understand. I'll spin that room up later and do my own testing.

**Comment by CheeseC4k3** [comment]
no problem, I just tested both commands and they both fix it.

**Comment by CheeseC4k3** [comment]
![image](https://user-images.githubusercontent.com/52067790/107529118-d6fe2100-6bba-11eb-8956-de63652b0457.png)
top one is stty sane, bottom is reset. stty sane is faster though.

**Comment by calebstewart** [comment]
Great to hear! I'll put together a fix for this later this afternoon, then. Should be relatively straightforward. Just need to figure out flags I want. I'll likely copy the flags that are used for `sane`.
