### ISSUE TITLE
[BUG] SSH to a url doesn't work

### ISSUE THREAD

**Issue by mTvare6** [calebstewart/pwncat#86]
**Describe the bug**
Syntax according to [readthedocs](https://pwncat.readthedocs.io/en/latest/usage.html#connecting-to-a-remote-ssh-server) isn't working for ssh to overthewire

**Describe the target system**
[Bandit from overthewire](https://overthewire.org/wargames/bandit/bandit0.html) 

**To Reproduce**
1. Check the [readthedocs](https://pwncat.readthedocs.io/en/latest/usage.html#connecting-to-a-remote-ssh-server).
2. It says `pwncat "ssh://bandit0:bandit0@bandit.labs.overthewire.org"` as the syntax for ssh
3. try connecting to overthewire using same syntax `pwncat "ssh://bandit0:bandit0@bandit.labs.overthewire.org"`

**Expected behavior**
Just a normal connection

**Screenshots**
![image](https://user-images.githubusercontent.com/57838468/108696968-4283af00-7528-11eb-89f0-f4aaf33b85c9.png)

Other methods I tried
![image](https://user-images.githubusercontent.com/57838468/108697071-60511400-7528-11eb-8cd3-92b8ba3b772b.png)
and syntax from [this issue](https://github.com/calebstewart/pwncat/issues/27)
![image](https://user-images.githubusercontent.com/57838468/108698383-16692d80-752a-11eb-8971-d07df51c64fe.png)

**Comment by calebstewart** [comment]
You appear to be using a different `pwncat`. Sadly, there is a naming conflict. You can find the other `pwncat` [here](https://github.com/cytopia/pwncat).

**Comment by mTvare6** [comment]
Oh, ye I forgot to source it, sorry
