### ISSUE TITLE
[BUG] Listener for lower ports throws an error

### ISSUE THREAD

**Issue by reybango** [calebstewart/pwncat#88]
**Describe the bug**
After installing pwncat into a virtual environment as outlined in the install instructions, I tried to create a listener on port 443. Doing so threw an error, which of course meant I needed to use 'sudo' due to a lower port range. But when typing in:

```sudo pwncat -l -p 443```

I received the following error:

```sudo: pwncat: command not found``` 

**Describe the target system**
Target system is the latest updated version of Kali: Linux kali 5.10.0-kali4-amd64 #1 SMP Debian 5.10.19-1kali1 (2021-03-03) x86_64 GNU/Linux

**To Reproduce**
1. Git clone the pwncat repo
2. Follow instructions to install in a python virtual environment
3. Type "sudo pwncat -l -p 443"

**Expected behavior**
The expected behavior would be a listener appearing for port 443 (or other lower port)

**Other Comments**
My guess is that this is a pathing issue based on where the pwncat setup routine installs the app.

```
env | grep ^PATH
PATH=/home/haribo/tools/pwncat/pwncat-env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/haribo/.local/bin

sudo env | grep ^PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by initinfosec** [comment]
> **Describe the bug**
> After installing pwncat into a virtual environment as outlined in the install instructions, I tried to create a listener on port 443. Doing so threw an error, which of course meant I needed to use 'sudo' due to a lower port range. But when typing in:
> 
> `sudo pwncat -l -p 443`
> 
> I received the following error:
> 
> `sudo: pwncat: command not found`
> 
> **Describe the target system**
> Target system is the latest updated version of Kali: Linux kali 5.10.0-kali4-amd64 #1 SMP Debian 5.10.19-1kali1 (2021-03-03) x86_64 GNU/Linux
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Git clone the pwncat repo
> 
>     2. Follow instructions to install in a python virtual environment
> 
>     3. Type "sudo pwncat -l -p 443"
> 
>     4. See error
> 
> 
> **Expected behavior**
> The expected behavior would be a listener appearing for port 443 (or other lower port)
> 
> **Other Comments**
> My guess is that this is a pathing issue based on where the pwncat setup routine installs the app.
> 
> ```
> env | grep ^PATH
> PATH=/home/haribo/tools/pwncat/pwncat-env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/haribo/.local/bin
> 
> sudo env | grep ^PATH
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ```

Hey Rey,

Ran into a similar issue myself - the following worked for me, but it does not feel clean at all:

1. create a venv as root and source it
2. install the pip requirements as both user and root
3. exit back to user and run it as sudo $(which pwncat) <cmd>

For ease-of-use, i'll probably alias pc to 'sudo $(which pwncat)'

**Comment by calebstewart** [comment]
Aliasing the command is an option. You can also symlink the pwncat binary from the virtual environment into a `bin` directory that is in the `sudo` PATH (e.g. `/usr/local/bin` is normally one of them) like this:

```sh
ln -s $(which pwncat) /usr/local/bin/pwncat
```

You don't need to call `activate` to use a binary within a virtual environment. The entrypoints installed by Python will recognize they need to be in a virtual environment and behave properly even if executed when it isn't activated.

**Comment by reybango** [comment]
@calebstewart that seems to have solved it. I removed pwncat and reinstalled following these steps:
```
1. git clone https://github.com/calebstewart/pwncat.git
2. python3 -m venv pwncat-env
3. source pwncat-env/bin/activate
4. pip install -U git+https://github.com/calebstewart/paramiko
5. pip install git+https://github.com/JohnHammond/base64io-python
6. python setup.py install
7. sudo ln -s /home/<user>/tools/pwncat/pwncat-env/bin/pwncat /usr/local/bin/pwncat
```

That solved it. Now I can use sudo to get a listener for lower ports. Thank you!

Perhaps this could be something that's a feature for the install script.

**Comment by calebstewart** [comment]
Regarding your suggestion, the actual installation directory is not configured by the Python package. While you technically *can* install files to arbitrary specific locations, it is not recommended, and will inevitably break things like Python virtual environments. The underlying "problem" is a security feature of `sudo` itself (ensuring a known-good `PATH` list), and the symlink is an acceptable workaround. I can probably add this as a note in the documentation as a potential hang-up and provide the symlink solution for future users, though.
