### ISSUE TITLE
Installation problem: importlib.metadata.PackageNotFoundError: pwncat [BUG]

### ISSUE THREAD

**Issue by VixieTSQ** [calebstewart/pwncat#93]
**Describe the bug**
This may be a result of my odd installation I used (but I believe I got the same issue installing it normally with pip aswell I could be wrong.) I used `--install-dir` with `easy_install` to put it in a custom directory but trying to run `pwncat` gives me the following error:

(I shortened paths)
```
Traceback (most recent call last):
  File "/opt/./pwncat", line 33, in <module>
    sys.exit(load_entry_point('pwncat==0.3.1', 'console_scripts', 'pwncat')())
  File "/opt/./pwncat", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pwncat
```

I looked at the `pwncat` file and it had the comment `# for compatibility with easy_install; see #2198` but I can't seem to find that issue anywhere (I assume it to be an issue because of the hashtag I could be wrong)

**Comment by calebstewart** [comment]
[easy_install has been deprecated since 2018](https://packaging.python.org/discussions/pip-vs-easy-install/) and is the most likely culprit of the botched install.

Do you have a specific reason for trying to use `easy_install` over the normal installation method?

**Comment by VixieTSQ** [comment]
@calebstewart 
> Do you have a specific reason for trying to use `easy_install` over the normal installation method?

`./setup.py install` does not have the option `--install-dir` but after just now looking `install` help page it does have `--prefix` and that is perfectly usable for me. However I gave it a try and when running pwncat again it gave me the same error.

Also I just realize why that comment was there. It's probably because this entry file was written as a part of another project for use in others. Just a guess.

**Comment by calebstewart** [comment]
The entrypoints aren't written by me. It's a feature of `setuptools` ([console_scripts](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html) to be specific).

Why do you want to install the package under a different prefix? This islikely not doing what you want (although I don't completely understand what you're trying to do or why). If you are simply trying to install pwncat and all it's dependencies in it's own environment, you should follow the official installation instructions, and install it within a virtual environment. If you simply want the `pwncat` entrypoint accessible to your path (or some other directory), then you can symlink the binary wherever you want, and it will work without entering the virtual environment. This isn't some magic implemented by pwncat, but is just a property of how virtual environments and console script entrypoints work.

**Comment by calebstewart** [comment]
I haven't heard anything in over a week. Let me know if there's more issues, but I'm going to close this, since it involves an unsupported installation method. I don't have any plans to support every arbitrary way to install Python modules. Good luck :+1:
