### ISSUE TITLE
[BUG] Sudo version enumeration seems to not detect sudo version

### ISSUE THREAD

**Issue by imprint-extract** [calebstewart/pwncat#98]
First of all, this tool is awesome! Thank you for creating it.

**Describe the bug**
When I am the msfadmin user on the metasploitable2 VM, and I attempt to do: ```escalate --user root run```, I encounter a ```ModuleFailed: no sudo version found``` exception.

However, when I do ```sudo -V``` in the metasploitable shell, I get ```Sudo version 1.6.9p10```

**Describe the target system**
The target system is a default Metasploitable2 VM running on my local host.

**Steps to reproduce the behavior:**
1. Launch an attack VM and a Metasploitable2 VM
2. From the attack VM: ```pwncat msfadmin@metasploitable2.vm```
3. In the pwncat session: ```(local) pwncat$ escalate --user root run```

**Expected behavior**
I would expect either a successful privesc, or a message saying that privesc had failed for another reason.

**Screenshot**
![Capture](https://user-images.githubusercontent.com/5056836/120588051-b79e3480-c3f3-11eb-872b-4f5e3d406c5d.PNG)

**Comment by calebstewart** [comment]
I was working on this issue this morning. I think I have a fix for this (and a few other things that cropped up while debugging). Please check out the issue. If possible, please clone that branch, and give it a test so I know it's working on your end before I merge. :+1:
